// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBKoQqVDSLaiGnS5uE2NcshN0NziP0wDE',
    appId: '1:266870219207:web:6ed0b9d9571224207679e2',
    messagingSenderId: '266870219207',
    projectId: 'uas-ppb-5',
    authDomain: 'uas-ppb-5.firebaseapp.com',
    storageBucket: 'uas-ppb-5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqhtEXxINnBAYCbPNvn4lzkbsBdLn_IUI',
    appId: '1:266870219207:android:9ef212f6c1951e7b7679e2',
    messagingSenderId: '266870219207',
    projectId: 'uas-ppb-5',
    storageBucket: 'uas-ppb-5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMpgB_fButBFLm9sZmPgtZOMiQcl_G4VE',
    appId: '1:266870219207:ios:6631df1d3ba288557679e2',
    messagingSenderId: '266870219207',
    projectId: 'uas-ppb-5',
    storageBucket: 'uas-ppb-5.appspot.com',
    iosBundleId: 'com.example.uasPpb5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMpgB_fButBFLm9sZmPgtZOMiQcl_G4VE',
    appId: '1:266870219207:ios:dae6d9f881fc90207679e2',
    messagingSenderId: '266870219207',
    projectId: 'uas-ppb-5',
    storageBucket: 'uas-ppb-5.appspot.com',
    iosBundleId: 'com.example.uasPpb5.RunnerTests',
  );
}
